[package]
name = "rayblaster"
version = "0.1.0"
edition = "2018"
authors = ["Harvey Hunt <harveyhuntnexus@gmail.com>"]

[dependencies]
cgmath = "0.9.1"
image = "0.10.0"
argparse = "0.2.1"
crossbeam = "0.3.0"
num_cpus = "1.6.2"
anyhow = "1.0.33"
